arch:
  - amd64
  - ppc64le
language: python

# workaround to make travis work with python3.7
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install -r requirements.txt
  - pip install -e .['dev']

script:
  - make
